### ISSUE TITLE
cannot run nextjs, after adding notion

### ISSUE THREAD

**Issue by IgorZimmermann** [kerwanp/contentlayer-source-notion#3]
I tried adding a notion database using contentlayer, but it gives me the same error every time.

```
Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║ 
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║ 
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-21T14:47:48.956Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-21T14:47:48.956Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-21T14:47:48.956Z) was spawned by:
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-21T14:47:48.955Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-21T14:47:48.955Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-21T14:47:48.955Z) was spawned by:
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-21T14:47:48.955Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-21T14:47:48.955Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-21T14:47:48.955Z) was spawned by:
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-21T14:47:48.953Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-21T14:47:48.953Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-21T14:47:48.953Z) was spawned by:
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-21T14:47:48.770Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-21T14:47:48.770Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-21T14:47:48.770Z) was spawned by:
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-21T14:47:48.763Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-21T14:47:48.763Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-21T14:47:48.763Z) was spawned by: <empty trace>
║  ▼
▼

OS: darwin 23.4.0 (arch: arm64)
Process: /opt/homebrew/Cellar/node/22.1.0/bin/node /Users/igorz/Documents/Developer/Coding/Projects/personal-website-2024/node_modules/next/dist/server/lib/start-server.js
Node version: v22.1.0
Contentlayer version: 0.3.4
```

**Comment by IgorZimmermann** [comment]
Resolved by downgrading `contentlayer` and `next-contentlayer` to version `0.3.2`.
